version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.application
    container_name: app
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}

