version: '3.1'

services:

  app:
    build:
      context: .
    container_name: app
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    command: sh /app/entrypoint.sh
    depends_on:
      - db

  celery:
    build:
      context: .
    container_name: celery
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
    command: celery worker -A dtf_bot -B --loglevel=info -c=4 # -P gevent
    depends_on:
      - db
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    volumes:
      - redis-data:/data
    
  # rabbitmq:
  #   image: "rabbitmq:latest"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   restart: always
  #   ports:
  #     - "15672:15672"
  #     - "${RABBIT_MQ_PORT}:5672"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
