# Generated by Django 2.2.1 on 2019-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='intro',
            field=models.CharField(max_length=512),
        ),
    ]
