# Generated by Django 2.2.1 on 2019-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190524_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.SmallIntegerField(null=True),
        ),
    ]
