# Generated by Django 2.2.1 on 2019-05-26 20:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190524_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('avatar_url', models.CharField(max_length=255, null=True)),
                ('karma', models.IntegerField()),
                ('user_hash', models.CharField(max_length=255)),
                ('last_response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
