# Generated by Django 2.2.1 on 2019-05-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='karma',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
