# Generated by Django 2.2.9 on 2020-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190526_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skipped',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.BigIntegerField()),
                ('object_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='skipped',
            constraint=models.UniqueConstraint(fields=('object_id', 'object_type'), name='unique_skipped'),
        ),
    ]
