# Generated by Django 2.2.9 on 2020-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200130_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipped',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
